releases:
  - name: ocf-scheduler
    version: 2.0.0
    url:     https://github.com/cloudfoundry-community/ocf-scheduler-boshrelease/releases/download/v2.0.0/ocf-scheduler-2.0.0.tgz
    sha1:    168c8f37fe0f040d46c0cdc38c14324936e52fe2