#!/bin/bash
set -u
#Version check
min_version="2.7.8-rc1"
genesis_version="$(genesis -v 2>&1 | grep '^Genesis v' | sed -e 's/Genesis v\(.*\) (.*$/\1/')"
if ! [[ "$genesis_version" =~ -dev$ ]] && ! new_enough "$genesis_version" "$min_version"; then
  describe >&2 "" "#R{[ERROR]} This kit needs Genesis $min_version.  Please upgrade before continuing" ""
  exit 1
fi
set -e

list() {
  describe "" "$(
    cat <<EOF
The following addons are defined:

  #G{bind-scheduler}   Binds the Scheduler service broker to your deployed CF.

  #G{setup-cf-plugin}   Adds the 'scheduler' plugin to the cf cli. Use #y{-f} option
                    to bypass confirmation prompt.

EOF
  )" ""
}

cf_login() {
  cf_deployment_env="$(exodus cf_deployment_env)"
  cf_deployment_type="$(exodus cf_deployment_type)"
  cf_exodus_path="${GENESIS_EXODUS_MOUNT}${cf_deployment_env}/${cf_deployment_type}"
  if ! cf plugins | grep -q '^cf-targets'; then
    describe "#Y{The cf-targets plugin does not seem to be installed}"
    echo "Install it first, via 'genesis do $GENESIS_ENVIRONMENT -- setup-cli'"
    echo "from your $cf_deployment_env environment in your CF deployment repo."
    exit 1
  fi

  system_domain="$(safe get "${cf_exodus_path}:system_domain")"
  api_url=https://api.$system_domain
  username="$(safe get "${cf_exodus_path}:admin_username")"
  password="$(safe get "${cf_exodus_path}:admin_password")"

  #TODO enfoce ssl validation
  cf api "$api_url" --skip-ssl-validation
  cf auth "$username" "$password"
  cf save-target -f "$cf_deployment_env"
  echo
  echo
  cf target
}

add_plugin() {
  cf_login
  describe "" "" "#Wkiu{Attempting to install latest version of the starkandwayne/ocf-scheduler-cf-plugin...}"
  existing="$(cf plugins --checksum | grep OCFScheduler | tr -s ' ' | cut -d ' ' -f 2)"
  cf install-plugin -r starkandwayne ocf-scheduler-cf-plugin "$@"
  updated="$(cf plugins --checksum | grep OCFScheduler | tr -s ' ' | cut -d ' ' -f 2)"
  if [[ -z "$updated" ]]; then
    echo
    exit 0
  fi
  if [[ "$existing" == "$updated" ]]; then
    describe "No update - existing ocf-scheduler-cf-plugin remains at version $existing" ""
    exit 0
  fi
  [[ -n "$existing" ]] && action="updated" || action="installed"
  header="$(cf plugins | head -n3 | tail -n1)"
  echo ""
  echo "$header"
  echo "$header" | sed -e 's/[^ ] [^ ]/xxx/g' | sed -e 's/[^ ]/-/g'
  cf plugins | grep OCFScheduler
  describe "" \
    "#G{[OK]} Successfully $action starkandwayne ocf-scheduler-cf-plugin." \
    "     You can run #c{cf uninstall-plugin OCFScheduler} to remove it."
  exit 0
}

bind_scheduler() {
  cf_login
  broker_username="$(exodus service_broker_username)"
  broker_password="$(exodus service_broker_password)"
  domain=$(exodus service_broker_domain)
  url="https://$domain"
  cf create-service-broker scheduler "$broker_username" "$broker_password" "$url"
  cf enable-service-access scheduler
  describe "" "#G{[OK]} Successfully created the service broker."
  exit 0
}

smoke::tests() {
  genesis "$GENESIS_ENVIRONMENT" bosh run-errand smoke-tests
}

case $GENESIS_ADDON_SCRIPT in
list) list ;;
smoketest | smoke-tests) smoke::tests ;;
setup-cf-plugin) add_plugin "$@" ;;
bind | bind-scheduler) bind_scheduler ;;
*)
  describe >&2 "" "#R{[ERROR]} No such addon: $GENESIS_ADDON_SCRIPT"
  list
  exit 1
  ;;
esac

exit 0
